// <auto-generated />
using System;
using GARBAGE.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GARBAGE.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230406170428_Migdration")]
    partial class Migdration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorModelItemModel", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "ItemsId");

                    b.HasIndex("ItemsId");

                    b.ToTable("AuthorModelItemModel");
                });

            modelBuilder.Entity("NameSpace.Models.AuthorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Img_idId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("ntext");

                    b.HasKey("Id");

                    b.HasIndex("Img_idId");

                    b.ToTable("author");
                });

            modelBuilder.Entity("NameSpace.Models.ImgModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("img");
                });

            modelBuilder.Entity("NameSpace.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("ntext");

                    b.Property<string>("Tags")
                        .HasColumnType("ntext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("item");
                });

            modelBuilder.Entity("NameSpace.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Img_idId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phonenumber")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Img_idId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Schimmel",
                            LastName = "Schimmel",
                            Phonenumber = 441506,
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Cruickshank",
                            LastName = "Cruickshank",
                            Phonenumber = 243479,
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Hodkiewicz",
                            LastName = "Hodkiewicz",
                            Phonenumber = 857827,
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Kub",
                            LastName = "Kub",
                            Phonenumber = 975219,
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "O'Conner",
                            LastName = "O'Conner",
                            Phonenumber = 484381,
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Denesik",
                            LastName = "Denesik",
                            Phonenumber = 846627,
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Schaden",
                            LastName = "Schaden",
                            Phonenumber = 164362,
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Cronin",
                            LastName = "Cronin",
                            Phonenumber = 854459,
                            Role = 2
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Bailey",
                            LastName = "Bailey",
                            Phonenumber = 740357,
                            Role = 2
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Price",
                            LastName = "Price",
                            Phonenumber = 159927,
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Feest",
                            LastName = "Feest",
                            Phonenumber = 312278,
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Tromp",
                            LastName = "Tromp",
                            Phonenumber = 124643,
                            Role = 2
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Renner",
                            LastName = "Renner",
                            Phonenumber = 468117,
                            Role = 1
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Gerlach",
                            LastName = "Gerlach",
                            Phonenumber = 763680,
                            Role = 1
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Hagenes",
                            LastName = "Hagenes",
                            Phonenumber = 669401,
                            Role = 2
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "White",
                            LastName = "White",
                            Phonenumber = 987935,
                            Role = 2
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Russel",
                            LastName = "Russel",
                            Phonenumber = 106020,
                            Role = 2
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Prosacco",
                            LastName = "Prosacco",
                            Phonenumber = 6825,
                            Role = 2
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Kirlin",
                            LastName = "Kirlin",
                            Phonenumber = 773277,
                            Role = 2
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Simonis",
                            LastName = "Simonis",
                            Phonenumber = 223903,
                            Role = 2
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Brakus",
                            LastName = "Brakus",
                            Phonenumber = 635287,
                            Role = 2
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Bogisich",
                            LastName = "Bogisich",
                            Phonenumber = 84227,
                            Role = 1
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Hoppe",
                            LastName = "Hoppe",
                            Phonenumber = 140532,
                            Role = 1
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Halvorson",
                            LastName = "Halvorson",
                            Phonenumber = 734882,
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Ankunding",
                            LastName = "Ankunding",
                            Phonenumber = 309575,
                            Role = 1
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Kutch",
                            LastName = "Kutch",
                            Phonenumber = 218194,
                            Role = 1
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Upton",
                            LastName = "Upton",
                            Phonenumber = 747918,
                            Role = 2
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Conroy",
                            LastName = "Conroy",
                            Phonenumber = 278150,
                            Role = 2
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Bogisich",
                            LastName = "Bogisich",
                            Phonenumber = 823036,
                            Role = 1
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Ruecker",
                            LastName = "Ruecker",
                            Phonenumber = 382851,
                            Role = 1
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "O'Kon",
                            LastName = "O'Kon",
                            Phonenumber = 397585,
                            Role = 2
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Bogisich",
                            LastName = "Bogisich",
                            Phonenumber = 431235,
                            Role = 2
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Zieme",
                            LastName = "Zieme",
                            Phonenumber = 487369,
                            Role = 2
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Predovic",
                            LastName = "Predovic",
                            Phonenumber = 915485,
                            Role = 2
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Robel",
                            LastName = "Robel",
                            Phonenumber = 426770,
                            Role = 2
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Christiansen",
                            LastName = "Christiansen",
                            Phonenumber = 694706,
                            Role = 2
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Auer",
                            LastName = "Auer",
                            Phonenumber = 861594,
                            Role = 2
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Haley",
                            LastName = "Haley",
                            Phonenumber = 943643,
                            Role = 1
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Hintz",
                            LastName = "Hintz",
                            Phonenumber = 256456,
                            Role = 1
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Fadel",
                            LastName = "Fadel",
                            Phonenumber = 192498,
                            Role = 1
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Schultz",
                            LastName = "Schultz",
                            Phonenumber = 659383,
                            Role = 1
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Kshlerin",
                            LastName = "Kshlerin",
                            Phonenumber = 952990,
                            Role = 2
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Christiansen",
                            LastName = "Christiansen",
                            Phonenumber = 729679,
                            Role = 1
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Kunde",
                            LastName = "Kunde",
                            Phonenumber = 588432,
                            Role = 1
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Feeney",
                            LastName = "Feeney",
                            Phonenumber = 784030,
                            Role = 2
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Lang",
                            LastName = "Lang",
                            Phonenumber = 20799,
                            Role = 2
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Jerde",
                            LastName = "Jerde",
                            Phonenumber = 763559,
                            Role = 2
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "MacGyver",
                            LastName = "MacGyver",
                            Phonenumber = 301274,
                            Role = 1
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Kiehn",
                            LastName = "Kiehn",
                            Phonenumber = 961647,
                            Role = 2
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Schowalter",
                            LastName = "Schowalter",
                            Phonenumber = 563128,
                            Role = 1
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Beahan",
                            LastName = "Beahan",
                            Phonenumber = 124577,
                            Role = 2
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Sauer",
                            LastName = "Sauer",
                            Phonenumber = 295319,
                            Role = 1
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Kutch",
                            LastName = "Kutch",
                            Phonenumber = 134460,
                            Role = 2
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Gerlach",
                            LastName = "Gerlach",
                            Phonenumber = 496333,
                            Role = 2
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Reinger",
                            LastName = "Reinger",
                            Phonenumber = 192542,
                            Role = 2
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Rath",
                            LastName = "Rath",
                            Phonenumber = 876726,
                            Role = 1
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Kreiger",
                            LastName = "Kreiger",
                            Phonenumber = 707951,
                            Role = 1
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Goyette",
                            LastName = "Goyette",
                            Phonenumber = 851967,
                            Role = 1
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Zboncak",
                            LastName = "Zboncak",
                            Phonenumber = 472614,
                            Role = 2
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Beahan",
                            LastName = "Beahan",
                            Phonenumber = 178491,
                            Role = 1
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Purdy",
                            LastName = "Purdy",
                            Phonenumber = 708059,
                            Role = 1
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Grant",
                            LastName = "Grant",
                            Phonenumber = 521064,
                            Role = 2
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Will",
                            LastName = "Will",
                            Phonenumber = 40818,
                            Role = 1
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Donnelly",
                            LastName = "Donnelly",
                            Phonenumber = 867158,
                            Role = 2
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Runolfsdottir",
                            LastName = "Runolfsdottir",
                            Phonenumber = 271066,
                            Role = 2
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Morissette",
                            LastName = "Morissette",
                            Phonenumber = 153158,
                            Role = 1
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Greenfelder",
                            LastName = "Greenfelder",
                            Phonenumber = 76697,
                            Role = 1
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Rodriguez",
                            LastName = "Rodriguez",
                            Phonenumber = 477820,
                            Role = 2
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Borer",
                            LastName = "Borer",
                            Phonenumber = 307982,
                            Role = 1
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Becker",
                            LastName = "Becker",
                            Phonenumber = 754735,
                            Role = 2
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Boyer",
                            LastName = "Boyer",
                            Phonenumber = 380432,
                            Role = 1
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Gerhold",
                            LastName = "Gerhold",
                            Phonenumber = 15271,
                            Role = 1
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Corwin",
                            LastName = "Corwin",
                            Phonenumber = 412210,
                            Role = 2
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Waelchi",
                            LastName = "Waelchi",
                            Phonenumber = 231305,
                            Role = 2
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Howell",
                            LastName = "Howell",
                            Phonenumber = 374253,
                            Role = 2
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Koch",
                            LastName = "Koch",
                            Phonenumber = 870781,
                            Role = 2
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "DuBuque",
                            LastName = "DuBuque",
                            Phonenumber = 653579,
                            Role = 1
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Armstrong",
                            LastName = "Armstrong",
                            Phonenumber = 300876,
                            Role = 2
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Haag",
                            LastName = "Haag",
                            Phonenumber = 523030,
                            Role = 1
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Altenwerth",
                            LastName = "Altenwerth",
                            Phonenumber = 955740,
                            Role = 1
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Emmerich",
                            LastName = "Emmerich",
                            Phonenumber = 656590,
                            Role = 1
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Anderson",
                            LastName = "Anderson",
                            Phonenumber = 577846,
                            Role = 2
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Hodkiewicz",
                            LastName = "Hodkiewicz",
                            Phonenumber = 532190,
                            Role = 1
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "White",
                            LastName = "White",
                            Phonenumber = 361560,
                            Role = 1
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Dach",
                            LastName = "Dach",
                            Phonenumber = 447425,
                            Role = 1
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Muller",
                            LastName = "Muller",
                            Phonenumber = 159309,
                            Role = 2
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Rodriguez",
                            LastName = "Rodriguez",
                            Phonenumber = 701613,
                            Role = 1
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Boyer",
                            LastName = "Boyer",
                            Phonenumber = 559480,
                            Role = 2
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Hilll",
                            LastName = "Hilll",
                            Phonenumber = 368529,
                            Role = 2
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Monahan",
                            LastName = "Monahan",
                            Phonenumber = 854743,
                            Role = 1
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Robel",
                            LastName = "Robel",
                            Phonenumber = 78367,
                            Role = 2
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Schowalter",
                            LastName = "Schowalter",
                            Phonenumber = 970578,
                            Role = 1
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Nader",
                            LastName = "Nader",
                            Phonenumber = 87181,
                            Role = 2
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Barton",
                            LastName = "Barton",
                            Phonenumber = 550235,
                            Role = 2
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Bernier",
                            LastName = "Bernier",
                            Phonenumber = 511927,
                            Role = 1
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Blick",
                            LastName = "Blick",
                            Phonenumber = 40577,
                            Role = 1
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Ziemann",
                            LastName = "Ziemann",
                            Phonenumber = 447171,
                            Role = 1
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Johnston",
                            LastName = "Johnston",
                            Phonenumber = 393544,
                            Role = 2
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Prosacco",
                            LastName = "Prosacco",
                            Phonenumber = 379971,
                            Role = 1
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Jenkins",
                            LastName = "Jenkins",
                            Phonenumber = 604022,
                            Role = 2
                        });
                });

            modelBuilder.Entity("AuthorModelItemModel", b =>
                {
                    b.HasOne("NameSpace.Models.AuthorModel", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NameSpace.Models.ItemModel", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NameSpace.Models.AuthorModel", b =>
                {
                    b.HasOne("NameSpace.Models.ImgModel", "Img_id")
                        .WithMany()
                        .HasForeignKey("Img_idId");

                    b.Navigation("Img_id");
                });

            modelBuilder.Entity("NameSpace.Models.UserModel", b =>
                {
                    b.HasOne("NameSpace.Models.ImgModel", "Img_id")
                        .WithMany()
                        .HasForeignKey("Img_idId");

                    b.Navigation("Img_id");
                });
#pragma warning restore 612, 618
        }
    }
}
